// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
