// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User2fa struct {
	ID        int32
	Enabled   pgtype.Bool
	Secret    pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserBase struct {
	ID        int32
	Email     string
	Password  pgtype.Text
	AuthType  int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserInfo struct {
	ID        int32
	Firstname pgtype.Text
	Lastname  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
