// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
)

const findOneProduct = `-- name: FindOneProduct :one
SELECT id, name, description, price, stock, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) FindOneProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, findOneProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
