// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, email string) (bool, error)
	GetUserLoginInfo(ctx context.Context, email string) (GetUserLoginInfoRow, error)
}

var _ Querier = (*Queries)(nil)
