// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_base.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT
  EXISTS (
    SELECT  id, email
    FROM  user_base
    WHERE email = $1
  )
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLoginInfo = `-- name: GetUserLoginInfo :one
SELECT id, email, "password", verify
FROM user_base
WHERE email = $1
`

type GetUserLoginInfoRow struct {
	ID       int32       `json:"id"`
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
	Verify   pgtype.Bool `json:"verify"`
}

func (q *Queries) GetUserLoginInfo(ctx context.Context, email string) (GetUserLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginInfo, email)
	var i GetUserLoginInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Verify,
	)
	return i, err
}

const updateUserVerifiedStatus = `-- name: UpdateUserVerifiedStatus :exec
UPDATE user_base
SET verify = TRUE
WHERE id = $1
`

func (q *Queries) UpdateUserVerifiedStatus(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateUserVerifiedStatus, id)
	return err
}

const userRegister = `-- name: UserRegister :one
WITH new_user AS (
  INSERT INTO
    user_base (email, "password", verify)
  VALUES
    ($1, $2, $3) RETURNING id
),
insert_user_info AS (
  INSERT INTO
    user_info (id, firstname, lastname)
  SELECT id, $4, $5
  FROM new_user
)
SELECT id
FROM new_user
`

type UserRegisterParams struct {
	Email     string      `json:"email"`
	Password  pgtype.Text `json:"password"`
	Verify    pgtype.Bool `json:"verify"`
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
}

func (q *Queries) UserRegister(ctx context.Context, arg UserRegisterParams) (int32, error) {
	row := q.db.QueryRow(ctx, userRegister,
		arg.Email,
		arg.Password,
		arg.Verify,
		arg.Firstname,
		arg.Lastname,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
