// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user-info.sql

package db

import (
	"context"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE EMAIL = $1
)
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLoginInfo = `-- name: GetUserLoginInfo :one
SELECT id, email, password
FROM users 
WHERE email = $1 and password = $2
`

type GetUserLoginInfoParams struct {
	Email    string
	Password string
}

type GetUserLoginInfoRow struct {
	ID       int32
	Email    string
	Password string
}

func (q *Queries) GetUserLoginInfo(ctx context.Context, arg GetUserLoginInfoParams) (GetUserLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginInfo, arg.Email, arg.Password)
	var i GetUserLoginInfoRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
