// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user-info.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
  SELECT 1 FROM user_base WHERE EMAIL = $1
)
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLoginInfo = `-- name: GetUserLoginInfo :one
SELECT id, email, password
FROM user_base 
WHERE email = $1
`

type GetUserLoginInfoRow struct {
	ID       int32       `json:"id"`
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) GetUserLoginInfo(ctx context.Context, email string) (GetUserLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginInfo, email)
	var i GetUserLoginInfoRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
