// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_base.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT
  EXISTS (
    SELECT  id, email
    FROM  user_base
    WHERE email = $1
  )
`

func (q *Queries) CheckUserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserLoginInfo = `-- name: GetUserLoginInfo :one
SELECT id, email, password
FROM user_base
WHERE email = $1
`

type GetUserLoginInfoRow struct {
	ID       int32       `json:"id"`
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) GetUserLoginInfo(ctx context.Context, email string) (GetUserLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginInfo, email)
	var i GetUserLoginInfoRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const userRegister = `-- name: UserRegister :one
WITH new_user AS (
  INSERT INTO
    user_base (email, "password", auth_type)
  VALUES
    ($1, $2, $3) RETURNING id
),
insert_user_info AS (
  INSERT INTO
    user_info (id, firstname, lastname)
  SELECT id, $4, $5
  FROM new_user
),
insert_user_2fa AS (
  INSERT INTO user_2fa (id, enabled, secret)
  SELECT id, $6, $7
  FROM new_user
)
SELECT id
FROM new_user
`

type UserRegisterParams struct {
	Email     string      `json:"email"`
	Password  pgtype.Text `json:"password"`
	AuthType  int16       `json:"auth_type"`
	Firstname string      `json:"firstname"`
	Lastname  string      `json:"lastname"`
	Enabled   pgtype.Bool `json:"enabled"`
	Secret    pgtype.Text `json:"secret"`
}

func (q *Queries) UserRegister(ctx context.Context, arg UserRegisterParams) (int32, error) {
	row := q.db.QueryRow(ctx, userRegister,
		arg.Email,
		arg.Password,
		arg.AuthType,
		arg.Firstname,
		arg.Lastname,
		arg.Enabled,
		arg.Secret,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
