// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_info.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finduserInfoById = `-- name: FinduserInfoById :one
SELECT firstname, lastname
FROM user_info
WHERE id = $1
`

type FinduserInfoByIdRow struct {
	Firstname pgtype.Text `json:"firstname"`
	Lastname  pgtype.Text `json:"lastname"`
}

func (q *Queries) FinduserInfoById(ctx context.Context, id int32) (FinduserInfoByIdRow, error) {
	row := q.db.QueryRow(ctx, finduserInfoById, id)
	var i FinduserInfoByIdRow
	err := row.Scan(&i.Firstname, &i.Lastname)
	return i, err
}
